import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../containers/Layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Solids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      test
    </Layout>
  );
};

export default Home;
